export const families = [
  { id: 1, name: 'ANSYS Design Suite Bundle' },
  { id: 2, name: 'Application Content' },
  { id: 3, name: 'AR Vuforia' },
  { id: 4, name: 'Connected Components Workbench' },
  { id: 5, name: 'Design Suite Toolkit' },
  { id: 6, name: 'Emulate 3D' },
  { id: 7, name: 'FactoryTalk Custom Historian' },
  { id: 8, name: 'FactoryTalk Analytics for Devices' },
  { id: 9, name: 'FactoryTalk Application Infrastructure Monitoring' },
  { id: 10, name: 'FactoryTalk AssetCentre' },
  { id: 11, name: 'FactoryTalk AutoSuite' },
  { id: 12, name: 'FactoryTalk Batch' },
  { id: 13, name: 'FactoryTalk CPGSuite, EIHub, Edge' },
  { id: 14, name: 'FactoryTalk Historian SE' },
  { id: 15, name: 'FactoryTalk Linx Gateway' },
  { id: 16, name: 'FactoryTalk Manufacturing Operations Management' },
  { id: 17, name: 'FactoryTalk MES Maintenance' },
  { id: 18, name: 'FactoryTalk Metrics' },
  { id: 19, name: 'FactoryTalk Network Manager' },
  { id: 20, name: 'FactoryTalk PharmaSuite' },
  { id: 21, name: 'FactoryTalk ProductionCentre' },
  { id: 22, name: 'FactoryTalk TeamONE' },
  { id: 23, name: 'FactoryTalk Transaction Manager' },
  { id: 24, name: 'FactoryTalk VantagePoint' },
  { id: 25, name: 'FactoryTalk View' },
  { id: 26, name: 'FactoryTalk Analytics' },
  { id: 27, name: 'Innovation Toolkit' },
  { id: 28, name: 'PlantPAx' },
  { id: 29, name: 'PTC Subscription' },
  { id: 30, name: 'RASWin' },
  { id: 31, name: 'Rockwell e-learning' },
  { id: 32, name: 'ThingWorx' },
  { id: 33, name: 'Scan ESC Lockout' },
  { id: 34, name: 'Studio5000 Application Code Manager' },
  { id: 35, name: 'Studio5000 Design Environment' },
  { id: 36, name: 'Studio5000 License Portal' },
  { id: 37, name: 'Test Recommended Brand' },
  { id: 38, name: 'ThinManager' },
  { id: 39, name: 'Threat Detector' }
]